### ISSUE TITLE
Scopes during identification?

### ISSUE THREAD

**Issue by skpy** [Inklings-io/selfauth#38] opened 2018-04-23 17:40 UTC
I'm trying out [grumble](https://github.com/jjdelc/grumble) a client-side Micropub client.  When it tries to perform IndieAuth against my `selfauth` endpoint, it spits this error:
```
Error: Faulty Request

There was an error with the request. The "scope" field cannot be used with identification.
```

As I am unfamiliar with Grumble, or client-side JS, it's not immediately clear to me if this is a bug with Grumble, or a deficiency with selfauth?  Help please? 🙏

**Comment by sknebel** [comment] 2018-04-23 17:42
What's the request URL you're getting this error from?

**Comment by skpy** [comment] 2018-04-23 17:45
```
https://skippy.rocks/auth?me=https%3A%2F%2Fskippy.rocks%2F&scope=create+update&client_id=https%3A%2F%2Findieauth.com%2F&redirect_uri=https%3A%2F%2Findieauth.com%2Fauth%2Findieauth%2Fredirect&state=c023a28509528df4ffe6a300d7df6c59
```

I'm using https://skippy.rocks/microclient/ as my Grumble install, and trying to IndieAuth to https://skippy.rocks, which will point to https://skippy.rocks/auth/

**Comment by aaronpk** [comment] 2018-04-23 17:50
How'd you manage to get to that URL? That looks like you're logging in somewhere on indieauth.com?

**Comment by aaronpk** [comment] 2018-04-23 18:12
We tracked this down to a caching bug in Grumble, which was caching the previously used indieauth.com authorization endpoint.

**Comment by sknebel** [comment] 2018-04-23 18:12
closing since @skpy confirmed in IRC that it now works (some browser caching issue apparently) and selfauth does the right thing for the badly formed URL above.

**Closed as completed by sknebel** 2018-04-23 18:12 UTC
