### ISSUE TITLE
Error: Faulty Request There was an error with the request. The "client_id" field is invalid.

### ISSUE THREAD

**Issue by CarlSinclair** [Inklings-io/selfauth#54] opened 2024-05-09 20:21 UTC
I've regenerated it several times and I keep getting the same error. Tried on a subdomain (http://auth.domain.tld and https://auth.domain.tld), on a subfolder (http://domain.tld/auth and https://domain.tld/auth) like in the guide, and even on the root domain (http://domain.tld and https://domain.tld). I even tried with www in the username (http://www.domain.tld and https://www.domain.tld).

`<?php`
`define('APP_URL', 'http://auth.domain.tld/');`
`define('APP_KEY', ''>`
`define('USER_HASH', '');`
`define('USER_URL', 'https://domain.tld');`

**Comment by CarlSinclair** [comment] 2024-05-09 21:57
I also got [php-mintoken](https://github.com/Zegnat/php-mintoken) set up but I don't see how it even connects to selfauth.

**Comment by Zegnat** [comment] 2024-05-13 07:30
You should not need to configure a separate token endpoint (such as Mintoken) if all you are trying to do is authenticate somewhere with your website as identity.

The config.php looks correct to me. I have the following set-up personally:

1. My homepage is `https://vanderven.se/martijn/`
2. That page contains a link to my authorization endpoint in the HTML, pointing at `https://vanderven.se/martijn/auth/`
3. On my server this is just a folder “auth” containing both index.php and config.php from Selfauth
4. The config.php sets `USER_URL` to `https://vanderven.se/martijn/` and `APP_URL` to `https://vanderven.se/martijn/auth/`

I can test this setup with https://indielogin.com/ by entering my website https://vanderven.se/martijn/. I am then redirected to my Selfauth instance and asked for a password.

Can you describe what you are trying to do? What is the result of entering your website into indielogin.com? Would you mind sharing your website so we can have a look?

**Comment by CarlSinclair** [comment] 2024-05-13 19:56
I'm trying to setup IndieAuth for its own sake and also for Webmentions.io
My website is https://carl-sinclair.com and I have selfauth currently setup at https://auth.carl-sinclair.com

Is it supposed to work by simply following the instructions in the readme? And if so, what could cause this `client_id` error to be thrown as "invalid"? The comment in `index.php` (where this error is being thrown from) says `client_id is either omitted or not a valid URL.`

Could this be due to the hyphen in the URL?

**Comment by CarlSinclair** [comment] 2024-05-18 18:24
@Zegnat any ideas?

**Comment by Zegnat** [comment] 2024-05-19 11:42
> My website is https://carl-sinclair.com/ and I have selfauth currently setup at https://auth.carl-sinclair.com/

It seems to work for me. When I enter https://carl-sinclair.com into https://indielogin.com/, I get the Selfauth login screen. I ofcourse do not know your password, so I cannot test it any further, but this suggests to me that you have configured things correctly: IndieLogin.com is able to detect that it needs to send me to https://auth.carl-sinclair.com/ and Selfauth prepares the login form.

It also seems to work with Webmention.io.

Any errors about a client are just that, problems with the client that you are trying to login to. But I am not able to reproduce that error with either IndieLogin.com nor Webmention.io. So I would ask again, what are you trying to do that is currently not working?

Are you trying to go to https://auth.carl-sinclair.com/ directly? That will not work, no. The login flow must be started by a client like Webmention.io. You need to go to wherever you want to login, like https://webmention.io/, and write the website you want to login as there. In your case https://carl-sinclair.com/. Then you will be sent over to Selfauth to handle the actual authentication.

So yes, it is supposed to work by simply following the instructions on the README. And to me it looks like you have followed all the instructions correctly.

**Comment by CarlSinclair** [comment] 2024-05-20 01:38
I have no idea what happened but yeah it's working now. Either the magic of leaving things alone or the fact that I added security headers to all my websites yesterday did the trick.

Thanks for the help.

**Comment by Zegnat** [comment] 2024-05-22 12:48
No problem! Hope you can now get into all the IndieWeb tools out there!

I will close this issue now. But do reach out if you run into any problems again 😄

**Closed as completed by Zegnat** 2024-05-22 12:48 UTC
